### PR TITLE
Alligned 2 inputs to center

### PR DESCRIPTION
**Pull request by Yasshu55**
Issue - #5   successfully Aligned 2 inputs to center
Screenshot (157)

### CODE REVIEW

**Comment by LunarMarathon** [comment]
Hey, I wanted it on the same line in the center

**Comment by Yasshu55** [comment]
> Hey, I wanted it on the same line in the center

ohhk I will make the changes and pr again

**Comment by Yasshu55** [comment]
@LunarMarathon I've made changes please check it

**Comment by LunarMarathon** [comment]
This is great! Thank you!

**Pull request merged**
