### PR TITLE
Added option for importing file

### PR DESCRIPTION
**Pull request by Aditi-1709**
Added the option for importing files as you mentioned in your issue.

### CODE REVIEW

**Comment by LunarMarathon** [comment]
Looks good but requires few changes - 
1. Add js part to js file
2. Change the styling for 'Browse...'
3. The regex isn't accepting 'graphTo2D(1).csv' - please modify such that it accepts
image
4. Append the existing table, don't create a new one

**Comment by Aditi-1709** [comment]
I have added everything you mentioned above except the 4th one, so can you
merge the rest? Maybe I can resolve the 4th one too but it'll take time as
I need to see because I don't know how to do that.

**Comment by LunarMarathon** [comment]
Um, no, there's no commit with the changes and take your time

**Comment by Aditi-1709** [comment]
Cool, I'll do it by today then. Don't assign this to anyone else please!
Also that button to upload i.e, this one is by default so I can't do any
changes to it. Okay ?

**Comment by LunarMarathon** [comment]
I'm not assigning to someone else, don't worry. They can be styled ex: 
image

**Comment by LunarMarathon** [comment]
@Aditi-1709 Hey, are you still working on this?

**Comment by Aditi-1709** [comment]
Yes, I am!

**Comment by Aditi-1709** [comment]
Added everything you asked for.

**Comment by Aditi-1709** [comment]
Any response?

**Comment by LunarMarathon** [comment]
@Aditi-1709 Hey, sorry I didn't have time to check these last few days. A new table is created rather than appending the existing table (tableArr) but that's fine, I'll try to use this array like a preview and later append it to the table with another button. Thanks for contributing!

**Comment by Aditi-1709** [comment]
Did u add hacktoberfest-accepted label? It is required so that it can be
considered in hacktoberfest!

**Pull request merged**
