### PR TITLE
Dark mode added to site

### PR DESCRIPTION
**Pull request by ElvinPero**
Dark mode toggle with a good animation has been added. Its applications in the site can easily be changed by simply editing css in future. Please merge it under **hacktoberfest-accepted**.

Issue no. #20 
image

### CODE REVIEW

**Comment by ElvinPero** [comment]
@LunarMarathon I have completed this issue

**Comment by ElvinPero** [comment]
@LunarMarathon currently the layout of the site looks pretty simple . I didnt add any preset so future issues can change the dark mode according to needs . For example bg color is yellow and font seems out of contrast , site doesnt look good . if I change dark mode acc to that then it will have to be changed again when good layout is added. I would suggest merge it  for now and let layout issue  #35 handle this since whole layout will be changed by that.

**Comment by ElvinPero** [comment]
@LunarMarathon whoever is handling issue #35 will take care of the dark mode acc to layout he designs for the dark mode , any alteration by me will be changed  and of no use once new layout is added . Thanks .

**Comment by LunarMarathon** [comment]
> Hey, there are 6-7 colors used right now, roughly how many will be used in dark mode? And there are hyperlinks now, and the text bg for checked check-boxes changes too. Please consider those and let me know. Or you can start and I'll suggest the changes that time

I had already mentioned this in the issue #20. You replied that you'd consider those so I assigned. This just changes the bg. And dark mode has to do with colors, any change to layout won't affect that

**Comment by ElvinPero** [comment]
> 

If you want i can change according to current site so dark mode works on current . I will do updation by tomorrow.. By layout I meant complete front page including colors.

**Comment by LunarMarathon** [comment]
Yep, it's for the current one and what you're asking me to ask from #35 is exactly what I asked for dark mode from you. 
And could you please paste the changes in newly cloned files? Please don't format it, it becomes difficult for me to find the changes. And add the js code to index.js, it shouldn't be in the html file. Take your time, thanks

**Comment by ElvinPero** [comment]
@LunarMarathon i have added the dark mode according to you. This is the result.
image
You can merge under hacktoberfest-accepted after checking.

**Comment by LunarMarathon** [comment]
The text isn't visible at all
image
image

What's wrong with the colors :/ please check other sites in dark mode and choose the colors accordingly (for both the text and the bg when checkbox is clicked)
image
image

The size of the toggle needs to be reduced, it's as big as the heading itself which usually isn't the case
image
look how small it usually is - 
image

**Comment by ElvinPero** [comment]
@LunarMarathon I have done the changes .kindly merge under hacktoberfest-accepted 
image

**Comment by ElvinPero** [comment]
@LunarMarathon Layout design had some place using default color so darkmode had problems in text , I fixed them

**Comment by ElvinPero** [comment]
@LunarMarathon Will check . fixed input issue and size of button fr now

**Comment by ElvinPero** [comment]
@LunarMarathon Completed every issue with dark mode

**Comment by ElvinPero** [comment]
@LunarMarathon Could you please merge it  now under hacktoberfest-accepted  since that requires a review of 7 days . i can change things after merge as well. Completed all the issues you pointed till now

**Comment by LunarMarathon** [comment]
Checkbox
image
Hover
image
Keyboard - down
image

**Comment by LunarMarathon** [comment]
Or it's fine, I'll merge it and change them myself. Thanks for contributing!

**Pull request merged**
