### PR TITLE
Centered the table

### PR DESCRIPTION
**Pull request by nileshlad09**
Hey @LunarMarathon  I centered the table as per issue #22

### CODE REVIEW

**Comment by LunarMarathon** [comment]
Um, why are they side by side ;-;
image

**Comment by nileshlad09** [comment]
image

@LunarMarathon now check

**Comment by LunarMarathon** [comment]
image
I'm at the start of the scroll bar but the column is not visible. Thought it might be a browser issue but it's the same on chrome too

**Comment by nileshlad09** [comment]
but I centered the div so there is no need to scroll

**Comment by LunarMarathon** [comment]
Can't see the column ;-; 
image

try margin: (whatever value is there right now) auto once
That should work

**Comment by nileshlad09** [comment]
check now @LunarMarathon

**Comment by LunarMarathon** [comment]
image
Remove your changes and add this 
[margin](margin: 20px auto;)

**Comment by LunarMarathon** [comment]
Ok, I'll edit and merge

**Comment by LunarMarathon** [comment]
Thanks for contributing!

**Comment by nileshlad09** [comment]
Thank you

**Pull request merged**
